// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutApp.API.Database;

#nullable disable

namespace WorkoutApp.API.Database.Migrations
{
    [DbContext(typeof(WorkoutAppDbContext))]
    partial class WorkoutAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkoutApp.API.Models.ScheduleDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleDayType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkoutScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutScheduleId");

                    b.ToTable("ScheduleDays", (string)null);

                    b.HasDiscriminator<string>("ScheduleDayType").HasValue("ScheduleDay");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WorkoutApp.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BaseUnit")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WorkoutApp.API.Models.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("WorkoutDayId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("WorkoutExercises", (string)null);

                    b.HasDiscriminator<string>("ExerciseType").HasValue("WorkoutExercise");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WorkoutApp.API.Models.WorkoutRepitition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentSuperSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RepititionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<TimeSpan?>("RestPeriod")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("WorkoutExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentSuperSetId");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("WorkoutRepititions", (string)null);

                    b.HasDiscriminator<string>("RepititionType").HasValue("WorkoutRepitition");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WorkoutApp.API.Models.WorkoutSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutSchedules");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.RestDay", b =>
                {
                    b.HasBaseType("WorkoutApp.API.Models.ScheduleDay");

                    b.HasDiscriminator().HasValue("Rest");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.WorkoutDay", b =>
                {
                    b.HasBaseType("WorkoutApp.API.Models.ScheduleDay");

                    b.HasDiscriminator().HasValue("Workout");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.TimedWorkout", b =>
                {
                    b.HasBaseType("WorkoutApp.API.Models.WorkoutExercise");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("WorkoutTime")
                        .HasColumnType("time");

                    b.HasDiscriminator().HasValue("TimedWorkout");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.WorkoutSetExercise", b =>
                {
                    b.HasBaseType("WorkoutApp.API.Models.WorkoutExercise");

                    b.Property<TimeSpan?>("RestPeriod")
                        .HasColumnType("time");

                    b.HasDiscriminator().HasValue("SetExercise");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.RepetitionCount", b =>
                {
                    b.HasBaseType("WorkoutApp.API.Models.WorkoutRepitition");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("WorkoutRepititions", t =>
                        {
                            t.Property("Weight")
                                .HasColumnName("RepetitionCount_Weight");
                        });

                    b.HasDiscriminator().HasValue("Count");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.SuperSetRepition", b =>
                {
                    b.HasBaseType("WorkoutApp.API.Models.WorkoutRepitition");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("SuperSet");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.TimedRepitition", b =>
                {
                    b.HasBaseType("WorkoutApp.API.Models.WorkoutRepitition");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Timed");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.ScheduleDay", b =>
                {
                    b.HasOne("WorkoutApp.API.Models.WorkoutSchedule", "WorkoutSchedule")
                        .WithMany("ScheduleDays")
                        .HasForeignKey("WorkoutScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSchedule");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.WorkoutExercise", b =>
                {
                    b.HasOne("WorkoutApp.API.Models.WorkoutDay", null)
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WorkoutApp.API.Models.WorkoutRepitition", b =>
                {
                    b.HasOne("WorkoutApp.API.Models.SuperSetRepition", null)
                        .WithMany("Exercises")
                        .HasForeignKey("ParentSuperSetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WorkoutApp.API.Models.WorkoutSetExercise", null)
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WorkoutApp.API.Models.WorkoutSchedule", b =>
                {
                    b.HasOne("WorkoutApp.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.WorkoutSchedule", b =>
                {
                    b.Navigation("ScheduleDays");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.WorkoutDay", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.WorkoutSetExercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("WorkoutApp.API.Models.SuperSetRepition", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
