using Microsoft.EntityFrameworkCore;
using System.Text;
using WorkoutApp.API.Database;
using WorkoutApp.API.Models;
using WorkoutApp.API.Models.Results;

namespace WorkoutApp.API.Services;

public interface IExerciseService
{
    Task<ServiceResult<Exercise>> GetWorkoutExerciseByIdAsync(Guid id, CancellationToken token = default);
    Task<ServiceResult<List<Exercise>>> GetWorkoutExercisesByScheduleDayIdAsync(Guid scheduleDayId, CancellationToken token = default);
    Task<ServiceResult<Exercise>> CreateWorkoutExerciseAsync(Exercise workoutExercise, CancellationToken token = default);
    Task<ServiceResult<Exercise>> UpdateWorkoutExerciseAsync(Exercise workoutExercise, CancellationToken token = default);
    Task<ServiceResult<bool>> DeleteWorkoutExerciseAsync(Guid id, CancellationToken token = default);
}

public class ExerciseService(WorkoutAppDbContext context) : IExerciseService
{
    private readonly string InternalServerErrorMessage = "An error occurred while processing your request.";
    public async Task<ServiceResult<Exercise>> GetWorkoutExerciseByIdAsync(Guid id, CancellationToken token = default)
    {
        try
        {
            var workoutExercise = await context.Exercises.FindAsync([id], token);
            if (workoutExercise == null)
                return new NotFoundResult<Exercise>($"WorkoutExercise with ID {id} not found.");
            return new SuccessResult<Exercise>(workoutExercise);
        }
        catch (Exception ex)
        {
            return new InternalServerErrorResult<Exercise>(InternalServerErrorMessage);
        }
    }

    public async Task<ServiceResult<List<Exercise>>> GetWorkoutExercisesByScheduleDayIdAsync(Guid scheduleDayId, CancellationToken token = default)
    {
        try
        {
            // Make sure the schedule day exists before querying for workout exercises
            var scheduleDay = await context.ScheduleDays.FindAsync([scheduleDayId], token);
            if (scheduleDay == null)
                return new NotFoundResult<List<Exercise>>($"ScheduleDay with ID {scheduleDayId} not found.");

            var query = context.Exercises
                .AsNoTracking()
                .Where(we => we.ScheduleDayId == scheduleDayId);
            if (!query.Any())
                return new NotFoundResult<List<Exercise>>("No workout exercises found for this schedule day.");

            var workoutExercises = await query
                .OrderByDescending(we => we.CreatedAt)
                .ToListAsync(token);
            return new SuccessResult<List<Exercise>>(workoutExercises);
        }
        catch (Exception ex)
        {
            return new InternalServerErrorResult<List<Exercise>>(InternalServerErrorMessage);
        }
    }

    public async Task<ServiceResult<Exercise>> CreateWorkoutExerciseAsync(Exercise workoutExercise, CancellationToken token = default)
    {
        try
        {
            // Make sure the schedule day exists before creating a workout exercise
            var scheduleDay = await context.ScheduleDays.FindAsync([workoutExercise.ScheduleDayId], token);
            if (scheduleDay == null)
                return new NotFoundResult<Exercise>("Cannot find a Schedule Day for the workout");

            // ID should not be provided when creating a new workout exercise, it will be generated by the database
            if (workoutExercise.Id != Guid.Empty)
                return new BadRequestResult<Exercise>("ID should not be provided when creating a new workout exercise.");

            // Workout-specific validation
            var validationResult = IsWorkoutExerciseValid(workoutExercise);
            if (!validationResult.Success)
                return validationResult;

            context.Exercises.Add(workoutExercise);
            await context.SaveChangesAsync(token);
            return new CreatedResult<Exercise>(workoutExercise);
        }
        catch (Exception ex)
        {
            return new InternalServerErrorResult<Exercise>(InternalServerErrorMessage);
        }
    }

    public async Task<ServiceResult<Exercise>> UpdateWorkoutExerciseAsync(Exercise workoutExercise, CancellationToken token = default)
    {
        try
        {
            // Make sure the workout exercise exists before updating
            var existingWorkoutExercise = await context.Exercises.FindAsync([workoutExercise.Id], token);
            if (existingWorkoutExercise == null)
                return new NotFoundResult<Exercise>($"WorkoutExercise with ID {workoutExercise.Id} not found.");

            // The ScheduleDayId cannot be changed when updating a workout exercise, it can only be changed by deleting and re-creating the workout exercise with the new ScheduleDayId
            if (workoutExercise.ScheduleDayId != existingWorkoutExercise.ScheduleDayId)
                return new BadRequestResult<Exercise>("ScheduleDayId cannot be changed when updating a workout exercise. To change the ScheduleDayId, delete and re-create the workout exercise with the new ScheduleDayId.");

            // Make sure that the workout exercise type is not being changed when updating
            if (workoutExercise.GetType() != existingWorkoutExercise.GetType())
                return new BadRequestResult<Exercise>("The workout exercise type cannot be changed when updating. To change the workout exercise type, delete and re-create the workout exercise with the new type.");

            var validationResult = IsWorkoutExerciseValid(workoutExercise);
            if (!validationResult.Success)
                return validationResult;

            // Update the existing workout exercise with the new values
            context.Entry(existingWorkoutExercise).CurrentValues.SetValues(workoutExercise);
            await context.SaveChangesAsync(token);
            return validationResult;
        }
        catch (Exception ex)
        {
            return new InternalServerErrorResult<Exercise>(InternalServerErrorMessage);
        }
    }

    public async Task<ServiceResult<bool>> DeleteWorkoutExerciseAsync(Guid id, CancellationToken token = default)
    {
        try
        {
            var workoutExercise = await context.Exercises.FindAsync([id], token);
            if (workoutExercise == null)
                return new NotFoundResult<bool>($"WorkoutExercise with ID {id} not found.");
            context.Exercises.Remove(workoutExercise);
            await context.SaveChangesAsync(token);
            return new SuccessResult<bool>(true);
        }
        catch (Exception ex)
        {
            return new InternalServerErrorResult<bool>(InternalServerErrorMessage);
        }
    }

    private static ServiceResult<Exercise> IsWorkoutExerciseValid(Exercise workoutExercise)
    {
        if (workoutExercise is TimedExercise timed)
        {
            if (timed.WorkoutTime <= TimeSpan.Zero)
                return new BadRequestResult<Exercise>("Workout time must be greater than zero.");
            if (timed.WorkoutTime.TotalDays > 1)
                return new BadRequestResult<Exercise>("Workout time cannot exceed 24 hours.");
        }
        else if (workoutExercise is SetExercise set)
        {
            if (set.RestPeriod.HasValue)
            {
                if (set.RestPeriod.Value <= TimeSpan.Zero)
                    return new BadRequestResult<Exercise>("Rest period must be greater than zero.");
                if (set.RestPeriod.Value.TotalDays > 1)
                    return new BadRequestResult<Exercise>("Rest period cannot exceed 24 hours.");
            }
        }
        else
            return new BadRequestResult<Exercise>("The provided workout exercise type is not supported.");
        return new SuccessResult<Exercise>();
    }
}
